service: helloService

provider:
  name: aws
  runtime: nodejs8.10
  stackName: test-stack
  apiName: test-api
#  deploymentBucket:
#    name: aperkkio.test.bucket
  versionFunctions: false
  endpointType: regional

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET temp

resources:
  Resources:
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          Enabled: "true"
          DefaultRootObject: "index.html"
# The default caching applies to the default (root) objects, not to images etc...
          DefaultCacheBehavior:
            AllowedMethods:
            - GET
            - HEAD
            MinTTL: "0"
            MaxTTL: "0"
            DefaultTTL: "0"
            TargetOriginId: myAPIOrigin
            ForwardedValues:
              QueryString: 'true'
              Cookies:
                Forward: all
            ViewerProtocolPolicy: redirect-to-https
            PathPattern: /api
# Here we define two behaviours of how we cache responses
          CacheBehaviors:
          - AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
            TargetOriginId: myS3Origin
            ForwardedValues:
              QueryString: "false"
            ViewerProtocolPolicy: https-only
            MinTTL: "0"
            MaxTTL: "6"
            DefaultTTL: "3"
# Here we define the API origin
          Origins:
            - DomainName:
               Fn::Join:
                - ""
                - - Ref: ApiGatewayRestApi
                  - ".execute-api.${self:provider.region}.amazonaws.com"
              Id: myAPIOrigin
              OriginPath: /${self:provider.stage}
              CustomOriginConfig:
                OriginProtocolPolicy: https-only
# Here's the origin from S3...
            - DomainName: aperkkio.test.s3.amazonaws.com
              ## An identifier for the origin which must be unique within the distribution
              Id: myS3Origin
              S3OriginConfig:
                OriginAccessIdentity: origin-access-identity/cloudfront/E319AJIF3O3H49
