service: service-one

provider:
  name: aws
  runtime: nodejs8.10
  stackName: test-stack
  apiName: test-api
  versionFunctions: false
  endpointType: regional

functions:
  functionOne:
    handler: functions/handlers.one
    events:
      - http:
          path: api/endpoint-one
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: Authorizer
  functionTwo:
    handler: functions/handlers.two
    events:
      - http:
          path: api/endpoint-two
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: Authorizer

resources:
  Resources:
    CloudFrontDistribution: ${file(./resources/cloudfront.yml)}
    Authorizer: ${file(./resources/cognito-authorizer.yml)}
    UserPool: ${file(./resources/cognito-userpool.yml)}
