service: service-one

plugins:
  - serverless-stack-output

custom:
  output:
    file: cf-output.json

provider:
  name: aws
  runtime: nodejs8.10
  apiName: test-api
  versionFunctions: false
  endpointType: regional

functions:
  getData: ${file(./functions/GetData/function-get-data.yml)}
  postData: ${file(./functions/PostData/function-post-data.yml)}

resources:
  Resources:
    CloudFrontDistribution: ${file(./resources/cloudfront.yml)}
    Authorizer: ${file(./resources/cognito-authorizer.yml)}
    UserPool: ${file(./resources/cognito-userpool.yml)}
    UserPoolClient: ${file(./resources/cognito-userpoolclient.yml)}
    DynamoDbTable: ${file(./resources/dynamodb-table.yml)}

  Outputs:
    CloudFrontDomainName:
      Value:
        Fn::GetAtt: ['CloudFrontDistribution', 'DomainName']
    CloudFrontDistrubutionId:
      Value:
        Ref: CloudFrontDistribution
    UserPoolClient:
      Value:
        Ref: UserPoolClient
    UserPool:
      Value:
        Ref: UserPool